name: 'dotnet-sonarcloud-analysis'
description: 'Run sonar scanner analysis on a dotnet core solution and collect opencover reports'
inputs:
  project-key:
    description: 'Specifies the key of the analyzed project in SonarCloud'
    required: true
  sonar-organization:
    description: 'Specifies the SonarCloud organization'
    required: true
  sonar-host-url:
    description: 'Specifies the access token to authenticate with to SonarCloud'
    required: true
  opencover-reports-paths:
    description: 'Path to OpenCover coverage reports'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.project-key }}
    - ${{ inputs.sonar-host-url }}
    - ${{ inputs.sonar-organization }}
    - ${{ inputs.opencover-reports-paths }}
    
branding:
  icon: 'check-circle'
  color: 'green'
